apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2022-04-16T20:03:05Z"
  name: resource-capacity
spec:
  description: A simple CLI that provides an overview of the resource requests, limits,
    and utilization in a Kubernetes cluster.
  homepage: https://github.com/robscott/kube-capacity
  platforms:
  - bin: kube-capacity
    files:
    - from: '*'
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 9881ca7336b5618390164e643dbdca4dd54d275ca8d6e587052473aad545dd34
    uri: https://github.com/robscott/kube-capacity/releases/download/v0.7.0/kube-capacity_0.7.0_Darwin_x86_64.tar.gz
  - bin: kube-capacity
    files:
    - from: '*'
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: 78fc70c2052d3f94a152f4ad78850d50badb9c137c456f9655abb5abe1f5f778
    uri: https://github.com/robscott/kube-capacity/releases/download/v0.7.0/kube-capacity_0.7.0_Darwin_arm64.tar.gz
  - bin: kube-capacity
    files:
    - from: '*'
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: a14039c9d677f291095c1164795c4016beae1f480d3bcb0b101ac79b0b72ed32
    uri: https://github.com/robscott/kube-capacity/releases/download/v0.7.0/kube-capacity_0.7.0_Linux_x86_64.tar.gz
  - bin: kube-capacity
    files:
    - from: '*'
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: linux
    sha256: a7cf6d17cb11f6b6eb3966443ca3db55437006a809a6a3851551550d07da0ac4
    uri: https://github.com/robscott/kube-capacity/releases/download/v0.7.0/kube-capacity_0.7.0_Linux_arm64.tar.gz
  - bin: kube-capacity.exe
    files:
    - from: '*'
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: cc5c9bf506544c4df69052802f8dd5a075d0dce42bcacedf03407de945a2d279
    uri: https://github.com/robscott/kube-capacity/releases/download/v0.7.0/kube-capacity_0.7.0_Windows_x86_64.tar.gz
  shortDescription: Provides an overview of resource requests, limits, and utilization
  version: v0.7.0
status:
  source:
    name: default
